#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=00:10:30
#SBATCH --output=/dev/null
#SBATCH --partition=optimum
module load python/3.12.0
source venev/bin/activate
mkdir ./data/generated/problems/paper/d40-08
mkdir ./data/generated/problems/paper/g30-10
mkdir ./data/generated/problems/paper/d35-02
mkdir ./data/generated/problems/paper/d50-08
mkdir ./data/generated/problems/paper/v45-06
mkdir ./data/generated/problems/paper/d45-07
mkdir ./data/generated/problems/paper/d30-01
mkdir ./data/generated/problems/paper/g35-03
mkdir ./data/generated/problems/paper/v40-02
mkdir ./data/generated/problems/paper/h45-06
mkdir ./data/generated/problems/paper/d45-09
mkdir ./data/generated/problems/paper/d30-02
mkdir ./data/generated/problems/paper/d35-04
mkdir ./data/generated/problems/paper/d30-04
mkdir ./data/generated/problems/paper/d45-03
mkdir ./data/generated/problems/paper/g30-06
mkdir ./data/generated/problems/paper/g45-10
mkdir ./data/generated/problems/paper/g50-06
mkdir ./data/generated/problems/paper/d40-01
mkdir ./data/generated/problems/paper/v45-07
mkdir ./data/generated/problems/paper/g30-09
mkdir ./data/generated/problems/paper/h35-02
mkdir ./data/generated/problems/paper/v30-03
mkdir ./data/generated/problems/paper/d40-09
mkdir ./data/generated/problems/paper/d45-06
mkdir ./data/generated/problems/paper/h45-09
mkdir ./data/generated/problems/paper/v50-03
mkdir ./data/generated/problems/paper/v45-10
mkdir ./data/generated/problems/paper/h40-04
mkdir ./data/generated/problems/paper/g35-02
mkdir ./data/generated/problems/paper/h45-01
mkdir ./data/generated/problems/paper/v35-08
mkdir ./data/generated/problems/paper/h30-04
mkdir ./data/generated/problems/paper/g40-04
mkdir ./data/generated/problems/paper/g30-03
mkdir ./data/generated/problems/paper/h30-10
mkdir ./data/generated/problems/paper/g50-10
mkdir ./data/generated/problems/paper/v35-03
mkdir ./data/generated/problems/paper/v35-01
mkdir ./data/generated/problems/paper/d30-09
mkdir ./data/generated/problems/paper/h30-08
mkdir ./data/generated/problems/paper/v50-04
mkdir ./data/generated/problems/paper/d45-05
mkdir ./data/generated/problems/paper/v45-02
mkdir ./data/generated/problems/paper/d50-10
mkdir ./data/generated/problems/paper/g45-02
mkdir ./data/generated/problems/paper/h50-03
mkdir ./data/generated/problems/paper/h35-03
mkdir ./data/generated/problems/paper/h30-01
mkdir ./data/generated/problems/paper/d45-10
mkdir ./data/generated/problems/paper/h30-05
mkdir ./data/generated/problems/paper/g40-06
mkdir ./data/generated/problems/paper/v50-01
mkdir ./data/generated/problems/paper/h35-07
mkdir ./data/generated/problems/paper/g45-08
mkdir ./data/generated/problems/paper/d35-05
mkdir ./data/generated/problems/paper/h45-07
mkdir ./data/generated/problems/paper/d50-02
mkdir ./data/generated/problems/paper/h45-08
mkdir ./data/generated/problems/paper/h50-07
mkdir ./data/generated/problems/paper/g30-07
mkdir ./data/generated/problems/paper/d45-04
mkdir ./data/generated/problems/paper/d40-07
mkdir ./data/generated/problems/paper/g50-04
mkdir ./data/generated/problems/paper/h40-07
mkdir ./data/generated/problems/paper/g30-05
mkdir ./data/generated/problems/paper/v30-01
mkdir ./data/generated/problems/paper/d35-06
mkdir ./data/generated/problems/paper/g40-09
mkdir ./data/generated/problems/paper/h30-03
mkdir ./data/generated/problems/paper/h50-01
mkdir ./data/generated/problems/paper/d50-01
mkdir ./data/generated/problems/paper/v45-05
mkdir ./data/generated/problems/paper/v35-09
mkdir ./data/generated/problems/paper/v45-09
mkdir ./data/generated/problems/paper/d35-01
mkdir ./data/generated/problems/paper/v50-10
mkdir ./data/generated/problems/paper/g50-09
mkdir ./data/generated/problems/paper/g30-04
mkdir ./data/generated/problems/paper/d35-07
mkdir ./data/generated/problems/paper/d30-10
mkdir ./data/generated/problems/paper/v30-05
mkdir ./data/generated/problems/paper/h50-02
mkdir ./data/generated/problems/paper/v30-07
mkdir ./data/generated/problems/paper/h40-01
mkdir ./data/generated/problems/paper/h40-02
mkdir ./data/generated/problems/paper/d35-10
mkdir ./data/generated/problems/paper/v40-06
mkdir ./data/generated/problems/paper/v50-09
mkdir ./data/generated/problems/paper/d40-05
mkdir ./data/generated/problems/paper/v40-08
mkdir ./data/generated/problems/paper/g50-07
mkdir ./data/generated/problems/paper/g45-06
mkdir ./data/generated/problems/paper/g35-06
mkdir ./data/generated/problems/paper/g30-08
mkdir ./data/generated/problems/paper/h50-09
mkdir ./data/generated/problems/paper/h50-08
mkdir ./data/generated/problems/paper/g45-05
mkdir ./data/generated/problems/paper/v40-01
mkdir ./data/generated/problems/paper/v45-08
mkdir ./data/generated/problems/paper/d40-06
mkdir ./data/generated/problems/paper/g40-01
mkdir ./data/generated/problems/paper/d40-10
mkdir ./data/generated/problems/paper/g40-03
mkdir ./data/generated/problems/paper/h30-06
mkdir ./data/generated/problems/paper/h30-02
mkdir ./data/generated/problems/paper/d45-02
mkdir ./data/generated/problems/paper/v40-04
mkdir ./data/generated/problems/paper/h40-03
mkdir ./data/generated/problems/paper/g40-10
mkdir ./data/generated/problems/paper/h35-05
mkdir ./data/generated/problems/paper/d50-03
mkdir ./data/generated/problems/paper/g35-05
mkdir ./data/generated/problems/paper/v40-09
mkdir ./data/generated/problems/paper/g40-05
mkdir ./data/generated/problems/paper/v35-07
mkdir ./data/generated/problems/paper/g50-05
mkdir ./data/generated/problems/paper/h35-09
mkdir ./data/generated/problems/paper/d30-08
mkdir ./data/generated/problems/paper/d30-06
mkdir ./data/generated/problems/paper/d45-01
mkdir ./data/generated/problems/paper/g35-07
mkdir ./data/generated/problems/paper/g30-02
mkdir ./data/generated/problems/paper/v40-10
mkdir ./data/generated/problems/paper/h40-08
mkdir ./data/generated/problems/paper/v45-01
mkdir ./data/generated/problems/paper/v40-07
mkdir ./data/generated/problems/paper/v50-02
mkdir ./data/generated/problems/paper/g30-01
mkdir ./data/generated/problems/paper/d50-09
mkdir ./data/generated/problems/paper/v50-05
mkdir ./data/generated/problems/paper/v35-02
mkdir ./data/generated/problems/paper/g50-01
mkdir ./data/generated/problems/paper/g50-08
mkdir ./data/generated/problems/paper/h40-10
mkdir ./data/generated/problems/paper/d45-08
mkdir ./data/generated/problems/paper/g35-01
mkdir ./data/generated/problems/paper/d40-02
mkdir ./data/generated/problems/paper/g40-02
mkdir ./data/generated/problems/paper/h30-07
mkdir ./data/generated/problems/paper/h40-05
mkdir ./data/generated/problems/paper/h35-10
mkdir ./data/generated/problems/paper/v50-07
mkdir ./data/generated/problems/paper/d30-05
mkdir ./data/generated/problems/paper/g50-02
mkdir ./data/generated/problems/paper/h30-09
mkdir ./data/generated/problems/paper/h35-08
mkdir ./data/generated/problems/paper/v30-04
mkdir ./data/generated/problems/paper/h45-10
mkdir ./data/generated/problems/paper/d35-03
mkdir ./data/generated/problems/paper/h40-09
mkdir ./data/generated/problems/paper/h40-06
mkdir ./data/generated/problems/paper/d40-04
mkdir ./data/generated/problems/paper/d30-07
mkdir ./data/generated/problems/paper/v30-08
mkdir ./data/generated/problems/paper/d35-08
mkdir ./data/generated/problems/paper/v40-03
mkdir ./data/generated/problems/paper/v30-10
mkdir ./data/generated/problems/paper/g35-04
mkdir ./data/generated/problems/paper/h45-03
mkdir ./data/generated/problems/paper/d50-06
mkdir ./data/generated/problems/paper/v50-06
mkdir ./data/generated/problems/paper/v35-05
mkdir ./data/generated/problems/paper/g50-03
mkdir ./data/generated/problems/paper/h50-05
mkdir ./data/generated/problems/paper/v45-03
mkdir ./data/generated/problems/paper/g35-09
mkdir ./data/generated/problems/paper/g45-07
mkdir ./data/generated/problems/paper/d50-04
mkdir ./data/generated/problems/paper/g40-07
mkdir ./data/generated/problems/paper/d35-09
mkdir ./data/generated/problems/paper/v40-05
mkdir ./data/generated/problems/paper/d50-05
mkdir ./data/generated/problems/paper/h35-06
mkdir ./data/generated/problems/paper/v50-08
mkdir ./data/generated/problems/paper/g45-03
mkdir ./data/generated/problems/paper/h35-01
mkdir ./data/generated/problems/paper/d30-03
mkdir ./data/generated/problems/paper/v35-04
mkdir ./data/generated/problems/paper/v35-06
mkdir ./data/generated/problems/paper/v30-06
mkdir ./data/generated/problems/paper/g45-09
mkdir ./data/generated/problems/paper/v45-04
mkdir ./data/generated/problems/paper/h35-04
mkdir ./data/generated/problems/paper/d40-03
mkdir ./data/generated/problems/paper/h45-02
mkdir ./data/generated/problems/paper/g45-04
mkdir ./data/generated/problems/paper/g45-01
mkdir ./data/generated/problems/paper/g35-10
mkdir ./data/generated/problems/paper/h50-10
mkdir ./data/generated/problems/paper/v30-02
mkdir ./data/generated/problems/paper/v35-10
mkdir ./data/generated/problems/paper/h50-04
mkdir ./data/generated/problems/paper/d50-07
mkdir ./data/generated/problems/paper/g40-08
mkdir ./data/generated/problems/paper/h50-06
mkdir ./data/generated/problems/paper/h45-04
mkdir ./data/generated/problems/paper/v30-09
mkdir ./data/generated/problems/paper/h45-05
mkdir ./data/generated/problems/paper/g35-08
sleep 600