#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=00:20:00
#SBATCH --output=/dev/null
#SBATCH --partition=optimum
mkdir ./data/generated/problems/paper/g30-10
mkdir ./data/generated/problems/paper/g35-03
mkdir ./data/generated/problems/paper/g30-06
mkdir ./data/generated/problems/paper/g45-10
mkdir ./data/generated/problems/paper/g50-06
mkdir ./data/generated/problems/paper/g30-09
mkdir ./data/generated/problems/paper/g35-02
mkdir ./data/generated/problems/paper/g40-04
mkdir ./data/generated/problems/paper/g30-03
mkdir ./data/generated/problems/paper/g50-10
mkdir ./data/generated/problems/paper/g45-02
mkdir ./data/generated/problems/paper/g40-06
mkdir ./data/generated/problems/paper/g45-08
mkdir ./data/generated/problems/paper/g30-07
mkdir ./data/generated/problems/paper/g50-04
mkdir ./data/generated/problems/paper/g30-05
mkdir ./data/generated/problems/paper/g40-09
mkdir ./data/generated/problems/paper/g50-09
mkdir ./data/generated/problems/paper/g30-04
mkdir ./data/generated/problems/paper/g50-07
mkdir ./data/generated/problems/paper/g45-06
mkdir ./data/generated/problems/paper/g35-06
mkdir ./data/generated/problems/paper/g30-08
mkdir ./data/generated/problems/paper/g45-05
mkdir ./data/generated/problems/paper/g40-01
mkdir ./data/generated/problems/paper/g40-03
mkdir ./data/generated/problems/paper/g40-10
mkdir ./data/generated/problems/paper/g35-05
mkdir ./data/generated/problems/paper/g40-05
mkdir ./data/generated/problems/paper/g50-05
mkdir ./data/generated/problems/paper/g35-07
mkdir ./data/generated/problems/paper/g30-02
mkdir ./data/generated/problems/paper/g30-01
mkdir ./data/generated/problems/paper/g50-01
mkdir ./data/generated/problems/paper/g50-08
mkdir ./data/generated/problems/paper/g35-01
mkdir ./data/generated/problems/paper/g40-02
mkdir ./data/generated/problems/paper/g50-02
mkdir ./data/generated/problems/paper/g35-04
mkdir ./data/generated/problems/paper/g50-03
mkdir ./data/generated/problems/paper/g35-09
mkdir ./data/generated/problems/paper/g45-07
mkdir ./data/generated/problems/paper/g40-07
mkdir ./data/generated/problems/paper/g45-03
mkdir ./data/generated/problems/paper/g45-09
mkdir ./data/generated/problems/paper/g45-04
mkdir ./data/generated/problems/paper/g45-01
mkdir ./data/generated/problems/paper/g35-10
mkdir ./data/generated/problems/paper/g40-08
mkdir ./data/generated/problems/paper/g35-08
sleep 600